name: deferred_lib_issue
description: An absolute bare-bones web app.
version: 1.0.1
repository: https://github.com/gmpassos/deferred_lib_issue
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  test: ^1.24.6

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^2.0.0
